<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LCLA" Version="0.0.10" />
  </ItemGroup>

    <ItemGroup>
    <EmbeddedResource
        Include="Data\ecg_1000.csv"
        LogicalName="BlazorServerExample.Data.ecg_1000.csv" />
    </ItemGroup>
</Project>
