<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Condition="'$(LclaUseLocalSource)' != 'true'">
    <PackageReference Include="LCLA" Version="0.0.9" />
  </ItemGroup>

  <ItemGroup Condition="'$(LclaUseLocalSource)' == 'true'">
    <ProjectReference Include="..\..\packages\clients\csharp\LightningChart.LA\LightningChart.LA.csproj" />
  </ItemGroup>

</Project>
